"""Conversation context assembly for long-running chats.

The database message rows remain the source of truth. This package builds the
bounded prompt context used by `/api/chat` and stores compact summaries when a
conversation grows beyond the configured budget.
"""
from __future__ import annotations

from src.memory.extract import (
    CONSTRAINT_TOPIC_ALIASES,
    CONSTRAINT_TOPICS,
    contains_sensitive_memory_content,
    constraint_topic_from_memory_key,
    extract_conversation_memory_candidates_with_llm,
    extract_explicit_memory_candidate,
    extract_memory_candidates,
    infer_constraint_topic,
    normalize_constraint_key,
)
from src.memory.long_term import (
    consolidate_user_memories,
    extract_conversation_memories,
    finalize_memory_rows_heavy,
    run_memory_heavy_background,
    store_explicit_user_memory,
    store_memory_candidates,
    store_user_memories,
)
from src.memory.retrieval import (
    backfill_user_memory_embeddings,
    memory_block,
    memory_embedding_is_available,
    refresh_memory_embedding,
    retrieve_user_memories,
)

from .builder import build_context_for_conversation
from .compression import (
    build_extractive_summary,
    ensure_summary_if_needed,
    get_latest_summary,
    prepare_summary_if_needed,
    run_summary_prepare_background,
    summarize_messages_with_llm,
)
from .constants import (
    DEFAULT_CONTEXT_WINDOW,
    DEFAULT_OUTPUT_TOKENS,
    FORCE_SUMMARY_RATIO,
    MAX_MEMORY_CONTEXT_TOKENS,
    MAX_MEMORY_EXTRACTION_SOURCE_CHARS,
    MAX_OUTPUT_TOKENS,
    MAX_PROFILE_CONTEXT_TOKENS,
    MAX_PROFILE_MEMORY_ROWS,
    MAX_SUMMARY_CONTEXT_TOKENS,
    MAX_SUMMARY_SOURCE_CHARS,
    MEMORY_CONFIDENCE_WEIGHT,
    MEMORY_CONSOLIDATE_SEMANTIC,
    MEMORY_IMPORTANCE_WEIGHT,
    MEMORY_INJECT_DEDUPE_COSINE,
    MEMORY_RETRIEVAL_LIMIT,
    MEMORY_SEMANTIC_MIN,
    MIN_OUTPUT_TOKENS,
    OUTPUT_TASK_TARGETS,
    OUTPUT_TOKEN_HARD_CAP,
    PREPARE_SUMMARY_RATIO,
    PROFILE_PREFERENCE_KEYS,
    RAG_RESERVE,
    RECENT_TURNS,
    SAFETY_RESERVE,
    SENSITIVE_PATTERNS,
    SUMMARY_TRIGGER_RATIO,
    SYSTEM_AND_TOOL_RESERVE,
    BuiltContext,
    ContextBudget,
    MemoryCandidate,
)
from .profile import build_user_memory_profile, user_profile_block
from .token_budget import (
    ContextBlockAllocation,
    ContextWindowResolution,
    ContextWindowSource,
    OutputTask,
    allocate_context_blocks,
    compute_budget,
    context_status_payload,
    context_window_for_model,
    estimate_effective_context_tokens,
    estimate_messages_tokens,
    estimate_tokens,
    rag_reserve_for_kb,
    resolve_context_window,
    resolve_output_token_budget,
    trim_messages_to_token_budget,
    truncate_text_to_token_budget,
)

__all__ = [
    "CONSTRAINT_TOPIC_ALIASES",
    "CONSTRAINT_TOPICS",
    "DEFAULT_CONTEXT_WINDOW",
    "DEFAULT_OUTPUT_TOKENS",
    "FORCE_SUMMARY_RATIO",
    "MAX_MEMORY_CONTEXT_TOKENS",
    "MAX_MEMORY_EXTRACTION_SOURCE_CHARS",
    "MAX_OUTPUT_TOKENS",
    "MAX_PROFILE_CONTEXT_TOKENS",
    "MAX_PROFILE_MEMORY_ROWS",
    "MAX_SUMMARY_CONTEXT_TOKENS",
    "MAX_SUMMARY_SOURCE_CHARS",
    "MEMORY_CONFIDENCE_WEIGHT",
    "MEMORY_CONSOLIDATE_SEMANTIC",
    "MEMORY_IMPORTANCE_WEIGHT",
    "MEMORY_INJECT_DEDUPE_COSINE",
    "MEMORY_RETRIEVAL_LIMIT",
    "MEMORY_SEMANTIC_MIN",
    "MIN_OUTPUT_TOKENS",
    "OUTPUT_TASK_TARGETS",
    "OUTPUT_TOKEN_HARD_CAP",
    "PREPARE_SUMMARY_RATIO",
    "PROFILE_PREFERENCE_KEYS",
    "RAG_RESERVE",
    "RECENT_TURNS",
    "SAFETY_RESERVE",
    "SENSITIVE_PATTERNS",
    "SUMMARY_TRIGGER_RATIO",
    "SYSTEM_AND_TOOL_RESERVE",
    "BuiltContext",
    "ContextBudget",
    "ContextBlockAllocation",
    "ContextWindowResolution",
    "ContextWindowSource",
    "MemoryCandidate",
    "OutputTask",
    "allocate_context_blocks",
    "backfill_user_memory_embeddings",
    "build_context_for_conversation",
    "build_extractive_summary",
    "build_user_memory_profile",
    "compute_budget",
    "consolidate_user_memories",
    "contains_sensitive_memory_content",
    "context_status_payload",
    "context_window_for_model",
    "constraint_topic_from_memory_key",
    "ensure_summary_if_needed",
    "estimate_effective_context_tokens",
    "estimate_messages_tokens",
    "estimate_tokens",
    "extract_conversation_memories",
    "extract_conversation_memory_candidates_with_llm",
    "extract_explicit_memory_candidate",
    "extract_memory_candidates",
    "finalize_memory_rows_heavy",
    "get_latest_summary",
    "infer_constraint_topic",
    "memory_block",
    "memory_embedding_is_available",
    "normalize_constraint_key",
    "rag_reserve_for_kb",
    "refresh_memory_embedding",
    "resolve_output_token_budget",
    "retrieve_user_memories",
    "prepare_summary_if_needed",
    "run_summary_prepare_background",
    "resolve_context_window",
    "run_memory_heavy_background",
    "store_explicit_user_memory",
    "store_memory_candidates",
    "store_user_memories",
    "summarize_messages_with_llm",
    "trim_messages_to_token_budget",
    "truncate_text_to_token_budget",
    "user_profile_block",
]
